apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: poc-onprem
type: Opaque
stringData:
  fernet-key: "q0xPBBjEFENFHslSCgZPb-XIT66kb27N36AtX7YNN94="
  internal-api-secret-key: "RqzCPqKJi7MxJZPaRThQuWvXkeW4F_tHdFo8ELBq3rI="
  jwt-secret: "RqzCPqKJi7MxJZPaRThQuWvXkeW4F_tHdFo8ELBq3rI="

# Made with Bob
