apiVersion: v1
kind: Secret
metadata:
  name: postgres-pdf-secrets
  namespace: poc-onprem
type: Opaque
stringData:
  postgres-user: "pdfuser"
  postgres-password: "pdfpassword"
  postgres-db: "pdfdb"

# Made with Bob
