apiVersion: v1
kind: Secret
metadata:
  name: postgres-airflow-secrets
  namespace: poc-onprem
type: Opaque
stringData:
  postgres-user: "airflow"
  postgres-password: "airflow"
  postgres-db: "airflow"

# Made with Bob
